"""
storage.py
----------
This file handles saving and loading all student data.
Data is stored as a plain Python list inside students_data.py
When you add a student, their record gets APPENDED to that list.
"""

import os

# This is the file where all student data will be saved
DATA_FILE = "students_data.py"


def load_students():
    """
    Read students_data.py and return the list of students.
    If the file does not exist yet, return an empty list.
    """
    if not os.path.exists(DATA_FILE):
        return []

    data = {}
    with open(DATA_FILE, "r") as f:
        exec(f.read(), data)

    return data.get("students", [])


def save_students(students):
    """
    Save the full student list back to students_data.py.
    This rewrites the file every time data changes.
    """
    with open(DATA_FILE, "w") as f:
        f.write("# All student data is stored here automatically.\n")
        f.write("# Do not edit this file by hand.\n\n")
        f.write("students = [\n")
        for s in students:
            f.write(f"    {repr(s)},\n")
        f.write("]\n")


def append_student(new_student):
    """
    Add a new student to the list and save.
    This is the APPEND operation.
    """
    students = load_students()
    students.append(new_student)
    save_students(students)


def get_next_id():
    """
    Auto-generate the next student ID.
    Starts at 1001 and goes up by 1 each time.
    """
    students = load_students()
    if not students:
        return 1001
    return max(s["id"] for s in students) + 1
