# All student data is stored here automatically.
# Do not edit this file by hand.

students = [
    {'id': 1001, 'name': 'bharat paliwal', 'grades': {'physics': 100, 'mathematics': 100, 'chemistry': 100}},
    {'id': 1002, 'name': 'SHUBHAM SAHU', 'grades': {'PHYSICS': 100, 'MATHEMATICS': 100, 'CHEMISTRY': 100}},
    {'id': 1003, 'name': 'Shreya Tripathi', 'grades': {'mathematics': 100, 'chemistry': 100, 'programming': 100}},
]
